[project]
name = "timeseries-tp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dtw-python>=1.7.2",
    "loadmydata>=0.0.11",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "seaborn>=0.13.2",
]
